<a href="https://colab.research.google.com/github/Dinoryong/hanaro01/blob/main/0612.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 기술통계

In [1]:
# 라이브러리 불러오기
import pandas as pd

In [2]:
# 데이터프레임 만들기
df = pd.DataFrame({'name': ["Richard", "Sara", "Andrea", "Steven", "Jordan", "Pam", 
                            "Michael", "Liz", "Nicole", "Mike", "Kent", "Elizabeth", 
                            "Bill", "Hadley", "Buffy", "Chip", "Homer", "Margaret", 
                            "Courtney", "Leonard", "Jeffrey", "Emily"],
                   'major': ["교육학", "심리학", "교육학", "심리학", "교육학", "교육학", 
                             "심리학", "심리학", "화학", "간호학", "역사학", "영어영문학", 
                             "심리학", "심리학", "교육학", "교육학", "심리학", "영어영문학", 
                             "심리학", "심리학", "화학", "스페인어"],
                   'age': [19, 18, 19, 21, 20, 24, 21, 19, 19, 20, 18, 21, 22, 23, 21, 19, 
                           18, 22, 24, 21, 18, 19]})
df

name  major  age
0     Richard    교육학   19
1        Sara    심리학   18
2      Andrea    교육학   19
3      Steven    심리학   21
4      Jordan    교육학   20
5         Pam    교육학   24
6     Michael    심리학   21
7         Liz    심리학   19
8      Nicole     화학   19
9        Mike    간호학   20
10       Kent    역사학   18
11  Elizabeth  영어영문학   21
12       Bill    심리학   22
13     Hadley    심리학   23
14      Buffy    교육학   21
15       Chip    교육학   19
16      Homer    심리학   18
17   Margaret  영어영문학   22
18   Courtney    심리학   24
19    Leonard    심리학   21
20    Jeffrey     화학   18
21      Emily   스페인어   19

In [3]:
# 전공 = 범주형 변수 => 빈도
# 최빈값 => 심리학
df['major'].value_counts()

심리학      9
교육학      6
화학       2
영어영문학    2
간호학      1
역사학      1
스페인어     1
Name: major, dtype: int64

In [4]:
# 나이 = 연속형 변수 => 평균
# 평균
df['age'].mean()

20.272727272727273

## 평균

In [5]:
customers = [2150, 1534, 3564]

In [6]:
(2150 + 1534 + 3564)/3

2416.0

In [7]:
import numpy as np

In [8]:
np.mean(customers)

2416.0

In [9]:
sum(customers)

7248

In [10]:
len(customers)

3

In [11]:
sum(customers)/len(customers)

2416.0

In [12]:
# 편차
x = [3,4,5]

In [13]:
x_bar = np.mean(x);x_bar

4.0

In [14]:
x_dev = x - x_bar;x_dev

array([-1.,  0.,  1.])

In [15]:
sum(x_dev)

0.0

In [16]:
# 가중평균
score = pd.Series([97, 94, 92, 91, 90, 89, 78, 60])
freq = pd.Series([4, 11, 12, 21, 30, 12, 9, 1])

In [17]:
# 점수*빈도
score_freq = score*freq

In [18]:
# 분자
sum(score_freq)

8967

In [19]:
# 분모
sum(freq)

100

In [20]:
# 가중 평균 = 분자 / 분모
sum(score_freq)/sum(freq)

89.67

In [21]:
# 산술평균
score.mean()

86.375

## 중앙값

In [22]:
x = pd.Series([135456, 54365, 37668, 32456, 25500])

In [23]:
# 오름 차순 정렬
x1 = x.sort_values()

In [24]:
# 중앙값
x1[2]

37668

In [25]:
# 함수로 찾아보기
x.median()

37668.0

In [26]:
x = pd.Series([135456, 54365, 37668, 34500, 32456, 25500])

In [27]:
# 오름 차순 정렬
x1 = x.sort_values()

In [28]:
# 중앙값
(x1[3] + x1[2])/2

36084.0

In [29]:
# 함수로 찾아보기
x.median()

36084.0

In [30]:
# 이상치와 평균
x = pd.Series([135456, 54365, 37668, 34500, 32456, 25500])

In [31]:
# 요약통계량
x.describe()

count         6.000000
mean      53324.166667
std       41366.292599
min       25500.000000
25%       32967.000000
50%       36084.000000
75%       50190.750000
max      135456.000000
dtype: float64

In [32]:
x.max()

135456

In [33]:
x[1:].mean()

36897.8

## 최빈값

In [34]:
# 1=민주당
# 2=공화당
# 3=무소속
party = pd.Series([1, 2, 3, 3, 3, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1])

In [35]:
# 범주형 변수 = 빈도표
party.value_counts()
# 최빈값 = 1=민주당

1    9
2    7
3    3
dtype: int64

In [36]:
# 1=빨간머리
# 2=금색머리
# 3=검정머리
# 4=갈색머리
hair = pd.Series([1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4])

In [37]:
# 범주형 변수 = 빈도표
hair.value_counts()
# 최빈값
# 3=검정머리
# 4=갈색머리

3    8
4    8
2    5
1    3
dtype: int64

In [38]:
# 최빈값을 찾아주는 함수
from scipy.stats import mode
mode(party)

<ipython-input-38-2b11971952b4>:3: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode(party)


ModeResult(mode=array([1]), count=array([9]))

In [39]:
mode(hair)
# 최빈값이 2개임에도 불구하고 3 하나만 알려줌

<ipython-input-39-1c4eac183bb8>:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode(hair)


ModeResult(mode=array([3]), count=array([8]))

In [40]:
# 최빈값이 2개 이상인 경우
from collections import Counter
count = Counter(hair)
count

Counter({1: 3, 2: 5, 3: 8, 4: 8})

In [41]:
freq = count.most_common()
freq

[(3, 8), (4, 8), (2, 5), (1, 3)]

In [42]:
# 값
freq[0][0]
freq[1][0]

4

In [43]:
# 빈도
freq[0][1]
freq[1][1]

8

In [44]:
max = freq[0][1]
max

8

In [45]:
mode = []
for i in freq:
  if i[1] == max:
    mode.append(i[0])
print(mode)

[3, 4]


In [46]:
# 최빈값을 알려주는 함수
from collections import Counter
def mode_mtp(data):
  count = Counter(data)
  freq = count.most_common()
  max = freq[0][1]
  mode = []
  for i in freq:
    if i[1] == max:
      mode.append(i[0])
  return mode

In [47]:
mode_mtp(hair)

[3, 4]

## 요약통계량

In [48]:
x = pd.Series([135456, 54365, 37668, 34500, 32456, 25500])

In [49]:
x.describe()

count         6.000000
mean      53324.166667
std       41366.292599
min       25500.000000
25%       32967.000000
50%       36084.000000
75%       50190.750000
max      135456.000000
dtype: float64

In [50]:
# 표준편차
x.std()

41366.29259876533

In [51]:
# 분산 = 표준편차 제곱
x.var()

1711170163.366667

In [52]:
# 중앙값
x.median()

36084.0

In [53]:
# 첨도, 왜도
from scipy.stats import skew, kurtosis
# 왜도
skew(x, bias = False)

2.1737564620024954

In [54]:
# 첨도
kurtosis(x, bias = False)

4.861219327469506

In [55]:
# 범위
x.max() - x.min()

109956

In [56]:
# min
# max
# sum
# len

## 문제 풀이

In [57]:
# 1
score1 = pd.Series([3, 7, 5, 4, 5, 6, 7, 8, 6, 5])
score2 = pd.Series([34, 54, 17, 26, 34, 25, 14, 24, 25, 23])
score3 = pd.Series([154, 167, 132, 145, 154, 145, 113, 156, 154, 123])

In [58]:
# 평균
print(score1.mean(), score2.mean(), score3.mean())

5.6 27.6 144.3


In [59]:
# 중앙값
print(score1.median(), score2.median(), score3.median())

5.5 25.0 149.5


In [60]:
# 최빈값
print(score1.value_counts(), score2.value_counts(), score3.value_counts())

5    3
7    2
6    2
3    1
4    1
8    1
dtype: int64 34    2
25    2
54    1
17    1
26    1
14    1
24    1
23    1
dtype: int64 154    3
145    2
167    1
132    1
113    1
156    1
123    1
dtype: int64


In [61]:
print(mode_mtp(score1), mode_mtp(score2), mode_mtp(score3))

[5] [34, 25] [154]


In [62]:
# 2
class1 = [23,15,34,32,33]
class2 = [32,44,15,44,36]
class3 = [17,12,27,19,23]

In [63]:
# 평균
print(np.mean(class1), np.mean(class2), np.mean(class3))

27.4 34.2 19.6


In [64]:
# 중앙값
print(np.median(class1), np.median(class2), np.median(class3))

32.0 36.0 19.0


In [65]:
# 3
data = pd.DataFrame({'burger': ["빅 버거","어린이 버거","치킨 버거","불고기 버거",
                                "일품 버거","핫도그"],
                     'quantity': [20,18,25,19,17,20],
                     'price': [2.95,1.49,3.50,2.95,1.99,1.99]})

In [66]:
# 판매금액
data['sales'] = data['quantity'] * data['price']

In [67]:
# 1) 가장 많이 팔린 버거는 치킨버거
data[data['sales'] == data['sales'].max()]

burger  quantity  price  sales
2  치킨 버거        25    3.5   87.5

In [68]:
# 2) 총 판매금액은 303 달러
data['sales'].sum()

303.0

In [69]:
# 3) 버거 하나당 평균 판매금액은 2.55 달러
round(data['sales'].sum() / data['quantity'].sum(), 2)

2.55

In [70]:
# 6, 7
df = pd.DataFrame({'toys': ["슬래머","레이더총","감자총"],
                   'month_7': [12345, 31454, 3253],
                   'month_8': [14453, 34567, 3121],
                   'month_9': [15435, 29678, 5131]})

In [71]:
# 장난감평균매출액
df.mean(axis = 1)

<ipython-input-71-7b387fbd6b68>:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean(axis = 1)


0    14077.666667
1    31899.666667
2     3835.000000
dtype: float64

In [72]:
# 월 평균매출액
df.mean()
# df.mean(axis = 0)

<ipython-input-72-b7846b5391b2>:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean()


month_7    15684.000000
month_8    17380.333333
month_9    16748.000000
dtype: float64

In [73]:
# 장남감 중앙값
df.median(axis = 1)

<ipython-input-73-cdbf1393437e>:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.median(axis = 1)


0    14453.0
1    31454.0
2     3253.0
dtype: float64

In [74]:
# 9
df = pd.DataFrame({'agegroup': ["0 ~ 4 세", "5 ~ 9 세", "10 ~ 14 세", "15 ~ 19 세"],
                   'week1': [12, 15, 12, 38],
                   'week2': [14, 12, 24, 12],
                   'week3': [15, 14, 21, 19]})

In [75]:
# 평균
df.mean()

<ipython-input-75-15aebfaeff61>:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean()


week1    19.25
week2    15.50
week3    17.25
dtype: float64

In [76]:
# 중앙값
df.median()

<ipython-input-76-266dd7a3c1db>:2: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.median()


week1    13.5
week2    13.0
week3    17.0
dtype: float64

In [77]:
# 10
df = pd.DataFrame({'학생': [1,2,3,4,5,6,7,8,9,10],
                     '퐁당과자': [1,5,7,1,5,6,2,5,7,3],
                     '컵케이크': [1,2,4,4,5,6,6,1,2,3],
                     '아이싱': [6,3,4,3,1,6,3,6,3,5],
                     '조립': [5,2,2,4,5,4,5,3,5,6],
                     '질감': [3,7,1,3,7,5,4,6,2,5]})

In [78]:
# 요약통계량
df.describe()

학생       퐁당과자       컵케이크        아이싱        조립         질감
count  10.00000  10.000000  10.000000  10.000000  10.00000  10.000000
mean    5.50000   4.200000   3.400000   4.000000   4.10000   4.300000
std     3.02765   2.299758   1.897367   1.699673   1.37032   2.057507
min     1.00000   1.000000   1.000000   1.000000   2.00000   1.000000
25%     3.25000   2.250000   2.000000   3.000000   3.25000   3.000000
50%     5.50000   5.000000   3.500000   3.500000   4.50000   4.500000
75%     7.75000   5.750000   4.750000   5.750000   5.00000   5.750000
max    10.00000   7.000000   6.000000   6.000000   6.00000   7.000000

In [79]:
# 표준편차
df.std()

학생      3.027650
퐁당과자    2.299758
컵케이크    1.897367
아이싱     1.699673
조립      1.370320
질감      2.057507
dtype: float64

In [80]:
# 분산
df.var()

학생      9.166667
퐁당과자    5.288889
컵케이크    3.600000
아이싱     2.888889
조립      1.877778
질감      4.233333
dtype: float64

In [81]:
# 첨도, 왜도
from scipy.stats import skew, kurtosis
# 왜도
skew(df, bias = False)

array([ 0.        , -0.30419709,  0.13176157, -0.16971589, -0.54407872,
       -0.12054955])

In [82]:
# 첨도
kurtosis(df, bias = False)

array([-1.2       , -1.45336286, -1.43812463, -0.83495351, -0.87196827,
       -1.08252217])